import Link from "next/link";
//import file "globals.css"
import "./globals.css"
import Image from "next/image";
// IMPORT fontAwesome
import "@fortawesome/fontawesome-svg-core/styles.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};    

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="corporate">  
      <body>
        {/*Area Header*/}
        <header>
          {/*Area Image/Banner*/}
          {/* <img src="../images/logo.png" alt="Logo UTI" /> */}
          <Image src={"/images/logo.png"} alt="Logo UTI" width={320} height={60} priority></Image>

          {/*Area Menu */}
          <nav className="text-center flex justify-center">
            <Link href={"/"} className="bg-red-500 hover:bg-red-700 text-white rounded-full px-5 py-2.5 mr-3 w-52"> Data Mahasiswa </Link>
            <Link href={"/"} className="bg-red-500 hover:bg-red-700 text-white rounded-full px-5 py-2.5 ml-3 w-52"> Log Data Mahasiswa </Link>
          </nav>

        </header>
        {/*Area Content*/}
        <section className="m-5">
        {children}
        </section>

        {/*Area Footer*/}
        <footer className="flex justify-center bg-color1 text-color3-2 py-15X mt-5">
          Copyright &copy; 2024 - RIFKI ABDULLAH

        </footer>
      </body>
    </html>
  );
}
